name: Test Examples

on:
  push:
    branches:
      - '*'
      - '*/*'
  pull_request:
    branches:
      - '*'
      - '*/*'

concurrency:
  group: test-examples-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment for Android build
        uses: ./.github/actions/prepare-env

      - name: Install
        run: cd projects && ./install.sh

      - name: Test Examples
        run: cd examples && ./test.sh

      - name: Upload test reports
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            '**/*/examples/android-perfs/build/reports/tests/testDebugUnitTest/'
